"""
7_🏛️_Strategy_Library.py — the curated list of strategies the dashboard
considers deployable, with their grid-sweep stats inline.

This is the "what should I deploy?" page. It's read-only — no buttons that
mutate state. The action lives on the Live tab (Page 3) and Operations
(Page 0). This page just gives the operator the data they need to decide.

Stats source: docs/grid_results.md (regenerated by `make sweep-grid`).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from core import strategy_library, edge_catalog   # noqa: E402
from dashboards.components import theme   # noqa: E402


def _run_drilldown(entry, *, start_bal: float, train_pct: float,
                    commission: float) -> None:
    """Run the entry's backtest live and render full stats + curves."""
    from core.backtest import partition_train_test, run_backtest
    from core.backtest_stats import (
        compute_full_stats, rescale_to_starting_balance,
    )
    from core.data import load_parquet
    from dashboards.components.state import discover_strategies

    parquet = REPO / "data" / f"{entry.ticker}_{entry.tf}.parquet"
    if not parquet.exists():
        st.error(f"Parquet `{parquet.relative_to(REPO)}` missing — "
                  "use Data Manager to fetch.")
        return

    strats = discover_strategies()
    base = entry.strategy
    for needle in ("_9_20", "_12_26", "_20_50", "_30_70",
                    "_20_2", "_55", "_20", "_10"):
        if base.endswith(needle):
            base = base[: -len(needle)]
            break
    if base not in strats:
        st.error(f"Strategy class `{base}` not found.")
        return
    StratCls, ParamsCls = strats[base]

    with st.spinner(f"Running {entry.strategy} on {entry.ticker} {entry.tf}…"):
        df = load_parquet(parquet)
        try:
            strat = (StratCls(ParamsCls(long_only=entry.long_only))
                     if ParamsCls is not None else StratCls())
        except TypeError:
            strat = StratCls()
        result = run_backtest(
            df, strat.signals(df),
            starting_balance=start_bal,
            lots=1.0, money_per_unit_price=1.0,
            commission_per_trade=commission,
            slippage_per_fill_atr_frac=0.1,
            symbol=entry.ticker,
        )
        stats = compute_full_stats(result, starting_balance=start_bal)

    # Reconciliation banner
    div = abs(result.sum_realized_pnl - result.equity_curve_pnl)
    if result.reconciles:
        st.success(f"✅ Reconciled — divergence ${div:.4f}")
    else:
        st.error(f"⛔ Reconciliation FAILED — divergence ${div:.2f}")

    if stats.n_trades == 0:
        st.warning("Strategy generated zero trades on this parquet.")
        return

    # Headline KPI grid
    k1 = st.columns(5)
    k1[0].metric("Trades", stats.n_trades)
    k1[1].metric("Win rate", f"{stats.win_rate_pct:.1f}%",
                    delta=f"{stats.n_wins}W / {stats.n_losses}L")
    k1[2].metric("Profit factor",
                    "inf" if stats.profit_factor == float("inf")
                    else f"{stats.profit_factor:.2f}")
    k1[3].metric("Avg R", f"{stats.avg_R:+.2f}")
    k1[4].metric("Net P&L", f"${stats.sum_realized:+,.2f}")

    k2 = st.columns(5)
    k2[0].metric("Max DD", f"{stats.max_dd_pct:.1f}%",
                    delta=f"-${stats.max_dd_dollars:,.0f}",
                    delta_color="inverse")
    k2[1].metric("DD duration", f"{stats.max_dd_duration_days:.0f}d")
    k2[2].metric("Recovery",
                    "not yet" if stats.recovery_duration_days is None
                    else f"{stats.recovery_duration_days:.0f}d")
    k2[3].metric("Max consec wins", stats.max_consec_wins)
    k2[4].metric("Max consec losses", stats.max_consec_losses,
                    delta_color="inverse")

    rr = stats.risk_reward_ratio
    k3 = st.columns(5)
    k3[0].metric("Avg win", f"${stats.avg_win_dollars:+,.2f}")
    k3[1].metric("Avg loss", f"${stats.avg_loss_dollars:+,.2f}",
                    delta_color="inverse")
    k3[2].metric("R:R ratio",
                    "inf" if rr == float("inf") else f"{rr:.2f}")
    k3[3].metric("Expectancy",
                    f"${stats.expectancy_dollars:+,.2f}")
    if stats.cagr_pct is None:
        k3[4].metric("CAGR (total)",
                       f"{(stats.sum_realized / start_bal * 100):+.1f}%")
    else:
        k3[4].metric("CAGR", f"{stats.cagr_pct:+.1f}%")

    # Equity + drawdown
    eq = rescale_to_starting_balance(result, start_bal)
    if eq is not None and not eq.empty:
        eq = eq.copy()
        eq["time"] = pd.to_datetime(eq["time"], utc=True, errors="coerce")
        eq = eq.dropna(subset=["time"]).sort_values("time")
        eq["peak"] = eq["equity"].cummax()
        eq["dd_pct"] = (eq["peak"] - eq["equity"]) / eq["peak"] * 100.0
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=eq["time"], y=eq["equity"],
                                    mode="lines", name="equity",
                                    line=dict(color="#38bdf8", width=2)))
        fig.add_hline(y=start_bal,
                       line=dict(color="#6b7280", dash="dash", width=1),
                       annotation_text=f"start ${start_bal:,.0f}",
                       annotation_position="top right",
                       annotation_font=dict(color="#6b7280", size=10))
        fig.add_hline(y=start_bal * 0.95,
                       line=dict(color="#dc2626", dash="dash", width=1),
                       annotation_text="−5% FTMO daily",
                       annotation_font=dict(color="#dc2626", size=10),
                       annotation_position="bottom right")
        fig.add_hline(y=start_bal * 0.90,
                       line=dict(color="#dc2626", dash="dash", width=1),
                       annotation_text="−10% FTMO total",
                       annotation_font=dict(color="#dc2626", size=10),
                       annotation_position="bottom right")
        fig.update_layout(
            title=f"Equity from ${start_bal:,.0f}",
            height=320, margin=dict(l=10, r=10, t=40, b=10),
            plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
            font=dict(color="#cbd5e1"),
            xaxis=dict(gridcolor="#1f2937"),
            yaxis=dict(gridcolor="#1f2937"))
        st.plotly_chart(fig, use_container_width=True)

        # R-distribution histogram
        rs = [t.r_multiple for t in result.trades]
        fig_r = go.Figure(go.Histogram(
            x=rs, nbinsx=30,
            marker_color="#38bdf8", opacity=0.85))
        fig_r.add_vline(x=0, line=dict(color="#6b7280", dash="dash"))
        fig_r.update_layout(
            title="R-multiple distribution",
            xaxis_title="R", yaxis_title="trades",
            height=240, margin=dict(l=10, r=10, t=40, b=10),
            plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
            font=dict(color="#cbd5e1"),
            xaxis=dict(gridcolor="#1f2937"),
            yaxis=dict(gridcolor="#1f2937"))
        st.plotly_chart(fig_r, use_container_width=True)

    # Train/Test split
    train, test = partition_train_test(result, train_pct, n_bars=len(df))
    st.markdown(f"**Train ({train_pct*100:.0f}%) / Test "
                  f"({(1 - train_pct)*100:.0f}%) split**")
    cols_split = st.columns(2)
    for col, m in [(cols_split[0], train), (cols_split[1], test)]:
        pf_disp = "inf" if m.profit_factor == float("inf") else f"{m.profit_factor:.2f}"
        col.markdown(
            f"<div style='background:#0f1419;border:1px solid #1f2937;"
            f"border-radius:8px;padding:10px;'>"
            f"<b>{m.label.upper()}</b> · n={m.n_trades} · "
            f"PF {pf_disp} · R {m.avg_R:+.2f} · "
            f"win {m.win_rate:.1f}% · ${m.sum_pnl:+,.0f}</div>",
            unsafe_allow_html=True)

    st.caption(
        f"Largest single win: ${stats.largest_win_dollars:+,.2f}  ·  "
        f"largest single loss: ${stats.largest_loss_dollars:+,.2f}  ·  "
        f"avg trade duration: {stats.avg_trade_bars:.1f} bars  ·  "
        f"sharpe-on-R: {stats.sharpe_R:.2f}"
    )


def _summary_metrics(entries: list[strategy_library.LibraryEntry]) -> None:
    """Top-of-page KPIs: how many recommended, survivors, total."""
    n = len(entries)
    n_rec = sum(1 for e in entries if e.recommended)
    n_edge = sum(1 for e in entries if e.has_edge)
    avg_test_r = (sum(e.edge.test_r for e in entries if e.edge)
                   / max(1, sum(1 for e in entries if e.edge)))
    cols = st.columns(4)
    cols[0].metric("Total cells", n)
    cols[1].metric("Recommended ⭐", n_rec)
    cols[2].metric("Survivors (edge)", n_edge)
    cols[3].metric("Avg test_R", f"{avg_test_r:+.2f}")


def _filter_controls() -> tuple[bool, bool, str, str]:
    cols = st.columns([1, 1, 2, 2])
    only_rec = cols[0].checkbox("⭐ Recommended only", value=False,
                                  key="lib_only_rec")
    only_edge = cols[1].checkbox("✅ With edge only", value=False,
                                   key="lib_only_edge")
    ticker_filter = cols[2].text_input(
        "ticker contains…", value="",
        placeholder="e.g. USDJPY or US100",
        key="lib_ticker_filter",
    )
    tf_filter = cols[3].selectbox(
        "tf", ["all", "M15", "H1", "H4", "D1"], index=0,
        key="lib_tf_filter",
    )
    return only_rec, only_edge, ticker_filter, tf_filter


def _table(entries: list[strategy_library.LibraryEntry]) -> pd.DataFrame:
    return strategy_library.to_dataframe(entries)


def _render_distribution_chart(
        entries: list[strategy_library.LibraryEntry]) -> None:
    """Scatter plot: train_R on x, test_R on y. Each cell is a point."""
    rows = [e for e in entries if e.edge is not None]
    if not rows:
        st.caption("(no edge data yet — run `make sweep-grid`)")
        return
    fig = go.Figure()
    for is_rec in (True, False):
        bucket = [e for e in rows if e.recommended == is_rec]
        if not bucket:
            continue
        fig.add_trace(go.Scatter(
            x=[e.edge.train_r for e in bucket],
            y=[e.edge.test_r for e in bucket],
            mode="markers",
            name=("⭐ Recommended" if is_rec else "Other"),
            marker=dict(
                size=[max(8, min(30, e.edge.n_test * 0.8)) for e in bucket],
                color=("#fbbf24" if is_rec else "#38bdf8"),
                opacity=0.85, line=dict(width=1, color="#0f1419"),
            ),
            text=[f"{e.strategy} · {e.ticker} · {e.tf} · "
                  f"PF {e.edge.test_pf:.2f} · n_test {e.edge.n_test}"
                  for e in bucket],
            hovertemplate="<b>%{text}</b><br>train_R %{x:+.2f}<br>"
                          "test_R %{y:+.2f}<extra></extra>",
        ))
    # Quadrant lines + survivor box
    fig.add_hline(y=0, line=dict(color="#374151", width=1, dash="dot"))
    fig.add_vline(x=0, line=dict(color="#374151", width=1, dash="dot"))
    fig.add_shape(
        type="rect", x0=0, y0=0, x1=2, y1=2,
        fillcolor="#16a34a", opacity=0.06,
        line=dict(color="#16a34a", width=1, dash="dot"),
    )
    fig.add_annotation(
        x=1.0, y=1.9, text="survivor zone (both > 0)",
        showarrow=False, font=dict(color="#16a34a", size=10),
    )
    fig.update_layout(
        title="train_R vs test_R — bigger = more OOS trades",
        xaxis_title="train avg R-multiple",
        yaxis_title="test avg R-multiple",
        height=460, plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
        font=dict(color="#cbd5e1"),
        legend=dict(orientation="h", x=0, y=1.10),
        margin=dict(l=10, r=10, t=60, b=10),
    )
    st.plotly_chart(fig, use_container_width=True)


def main() -> None:
    st.set_page_config(page_title="Strategy Library", page_icon="🏛️",
                        layout="wide")
    theme.inject_css()
    st.title("🏛️  Strategy Library")
    st.caption(
        "Each row is a strategy × ticker × timeframe cell. Stats come from "
        "the latest `make sweep-grid` run on real broker data. The "
        "⭐ rows are the curated portfolio that pre-fills on the **Live** "
        "tab.")

    cat = edge_catalog.load_catalog()
    if not cat:
        st.warning(
            "No edge data found. Run `make sweep-grid` (with the bridge "
            "running and parquets fresh) to populate "
            "`docs/grid_results.md`. Until then the Library shows the "
            "curated entries with no stats.")

    only_rec, only_edge, ticker_filter, tf_filter = _filter_controls()

    entries = strategy_library.list_library()
    if only_rec:
        entries = [e for e in entries if e.recommended]
    if only_edge:
        entries = [e for e in entries if e.has_edge]
    if ticker_filter.strip():
        ticker_filter_l = ticker_filter.strip().lower()
        entries = [e for e in entries
                    if ticker_filter_l in e.ticker.lower()]
    if tf_filter != "all":
        entries = [e for e in entries if e.tf == tf_filter]

    _summary_metrics(entries)
    st.markdown("")
    _render_distribution_chart(entries)
    st.markdown("---")

    st.markdown("### Cells ranked by out-of-sample R")
    df = _table(entries)
    if df.empty:
        st.caption("(no entries after filters)")
        return
    # Style: green for positive R / PF, red for negative
    def _color_r(v):
        try:
            f = float(v)
        except (TypeError, ValueError):
            return "color: #9ca3af;"
        if f > 0:
            return "color: #16a34a; font-weight: 600;"
        if f < 0:
            return "color: #dc2626; font-weight: 600;"
        return "color: #9ca3af;"

    styled = df.style.map(_color_r,
                            subset=["R_test", "R_train", "PF_test", "PF_train"])
    st.dataframe(styled, use_container_width=True,
                   height=min(720, 38 * (len(df) + 1)))

    # ── Drill-down panel: pick a cell, run the backtest inline, show
    # full stats + equity curve + drawdown.
    st.markdown("---")
    st.markdown("### 🔍  Deep-dive into a cell")
    st.caption(
        "Pick any cell to run its backtest live and see equity curve, "
        "drawdown, R distribution, and the full stats grid.")
    if not entries:
        st.caption("(no entries to drill into)")
    else:
        labels = {f"{e.strategy} · {e.ticker} · {e.tf}"
                  + (" ⭐" if e.recommended else ""): e for e in entries}
        choice = st.selectbox(
            "cell", options=list(labels.keys()),
            key="lib_drilldown_pick",
        )
        cols_in = st.columns([1, 1, 1])
        start_bal = float(cols_in[0].number_input(
            "Starting balance ($)", value=100_000.0,
            step=10_000.0, min_value=1_000.0,
            key="lib_drill_start"))
        train_pct = float(cols_in[1].slider(
            "Train split %", min_value=0.5, max_value=0.9,
            value=0.6, step=0.05, key="lib_drill_train"))
        comm = float(cols_in[2].number_input(
            "Commission $/trade", value=3.0, step=0.5,
            key="lib_drill_comm"))
        if st.button("▶  Run deep-dive backtest", type="primary",
                       key="lib_drill_run"):
            entry = labels[choice]
            _run_drilldown(entry, start_bal=start_bal,
                            train_pct=train_pct, commission=comm)

    st.markdown("---")
    st.markdown(
        "### How to use\n\n"
        "1. **Operations** (Page 0) — manage the deployments + accounts you "
        "actually run.\n"
        "2. **Strategy Library** (this page) — see the data behind every "
        "candidate, decide which to enable.\n"
        "3. **Live tab** (Page 3) — pick survivors with one click and push "
        "them into your active account's deployments.\n\n"
        "*Re-rank by running* `make sweep-grid` *after refreshing data on "
        "the Data Manager page.*"
    )


main()
