"""
7_🏛️_Strategy_Library.py — the curated list of strategies the dashboard
considers deployable, with their grid-sweep stats inline.

This is the "what should I deploy?" page. It's read-only — no buttons that
mutate state. The action lives on the Live tab (Page 3) and Operations
(Page 0). This page just gives the operator the data they need to decide.

Stats source: docs/grid_results.md (regenerated by `make sweep-grid`).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from core import strategy_library, edge_catalog   # noqa: E402
from core import account_manager, cost_defaults, deployment as dep_mod   # noqa: E402
from core.parity_gate import ParityGate   # noqa: E402
from dashboards.components import theme   # noqa: E402


def _add_single_to_account(entry, *, status: str,
                              quality_override_token: str = "") -> None:
    """Add ONE strategy from the library to the active account's
    deployments.json. Two gates apply:

      1. **Quality gate** — refuses to add a cell with no edge,
          excessive drawdown, never-recovered DD, etc. BLOCK can ONLY
          be bypassed when quality_override_token == "I UNDERSTAND".
      2. **Parity gate** — Live status falls back to paper if no
          recent replay-parity pass (variant resolved to base name).
    """
    from core.deployment_quality_gate import (
        evaluate_quality, load_criteria, QualityCriteria,
    )
    from dashboards.components.state import discover_strategies
    from dashboards.components.strategy_resolver import resolve_base_strategy

    try:
        accounts = account_manager.list_accounts()
        active = accounts[0] if accounts else None
    except Exception:
        active = None
    if active is None:
        st.error("No MT5 account configured — add one on Operations page.")
        return

    # ── Quality gate — first defence ─────────────────────────────────
    es = entry.edge
    if es is not None:
        # Live = strict criteria. Paper = lenient (allows experimentation).
        if status == "live":
            criteria = load_criteria(active.login)
        else:
            criteria = QualityCriteria.lenient()
        qres = evaluate_quality(es, criteria=criteria)
        if qres.is_blocked:
            if quality_override_token != "I UNDERSTAND":
                st.error(
                    f"⛔ **Deploy BLOCKED — failed {len(qres.block_reasons)} "
                    f"quality check(s)** for `{entry.strategy}` × "
                    f"`{entry.ticker}` × `{entry.tf}` ({status}):"
                )
                for reason in qres.block_reasons:
                    st.markdown(f"- {reason}")
                st.markdown(
                    "**Override (NOT recommended):** type "
                    "`I UNDERSTAND` in the override box on the page and "
                    "click again. The gate exists because these specific "
                    "issues mean the strategy is mathematically losing or "
                    "FTMO-incompatible — overriding will most likely cost "
                    "you the account."
                )
                return
            # Override path — log it, deploy as paper regardless of status
            st.warning(
                f"⚠ Quality BLOCK overridden by user. "
                f"Forcing **paper** mode for safety regardless of "
                f"requested {status} — promote later via Paper page only "
                f"if you've verified live conditions are OK."
            )
            status = "paper"
        elif qres.verdict == "WARN":
            for w in qres.warn_reasons:
                st.warning(f"🟡 Quality WARN: {w}")

    # ── Parity gate — second defence ────────────────────────────────
    gate = ParityGate(REPO / "data" / "v2.db")
    base_strat = (resolve_base_strategy(entry.strategy, discover_strategies())
                   or entry.strategy)
    actual = status
    if status == "live" and not gate.is_recent(base_strat):
        actual = "paper"
        st.warning(
            f"⚠ `{base_strat}` (base of variant `{entry.strategy}`) "
            f"has no recent replay-parity pass. Falling back to "
            f"**paper** instead of live. Click **🔬 Run replay-parity** "
            f"on this page to unblock."
        )
    dep_id = (dep_mod.Deployment.slug(entry.strategy, entry.ticker, entry.tf)
              + ("_long" if entry.long_only else "_bidir"))
    es = entry.edge
    risk_default = 0.30
    cap_default = 1.0
    notes = entry.why or ""
    if es:
        notes = (f"From Strategy Library — n_test {es.n_test}, "
                  f"PF {es.test_pf:.2f}, R {es.test_r:+.2f}, "
                  f"P(pass) {(es.p_pass_30d or 0)*100:.0f}%."
                  + (f"  {entry.why}" if entry.why else ""))
    d = dep_mod.Deployment(
        deployment_id=dep_id,
        strategy=entry.strategy,
        ticker=entry.ticker, tf=entry.tf,
        long_only=entry.long_only,
        params={"long_only": entry.long_only},
        risk_pct=risk_default, daily_cap_pct=cap_default,
        status=actual, notes=notes,
    )
    dep_mod.upsert_deployment(active.login, d)
    st.success(
        f"✅ Added `{dep_id}` as {actual.upper()} on #{active.login}. "
        f"Tweak risk%/cap% on the {actual.title()} page."
    )
    st.toast(f"deployed as {actual}")


def _run_replay_parity_inline(entry) -> None:
    """Run replay-parity for the selected library row inline. PASS
    records to the gate so the Live page / deploy buttons unblock.
    """
    import time
    from core.config import load_config
    from core.data import load_parquet
    from core.parity_check import run_parity
    from core.symbol_info_loader import try_load as try_load_symbol_info
    from dashboards.components.state import (
        DEFAULT_LOTS, DEFAULT_MONEY_PER_UNIT, resolve_money_per_unit, discover_strategies,
    )
    from dashboards.components.strategy_resolver import resolve_base_strategy

    strategies = discover_strategies()
    base = resolve_base_strategy(entry.strategy, strategies) or entry.strategy
    if base not in strategies:
        st.error(f"⛔ Base strategy `{base}` not registered.")
        return
    parquet = REPO / "data" / f"{entry.ticker}_{entry.tf}.parquet"
    if not parquet.exists():
        st.error(f"⛔ No parquet for {entry.ticker} {entry.tf} — fetch via "
                  f"Data Manager first.")
        return
    StratCls, ParamsCls = strategies[base]
    try:
        strat = StratCls() if ParamsCls is None else StratCls(ParamsCls())
    except Exception as e:
        st.error(f"⛔ Could not instantiate `{base}`: {e}")
        return
    cfg = load_config()
    df = load_parquet(parquet)
    sym_info = try_load_symbol_info(entry.ticker)
    t0 = time.time()
    with st.spinner(f"Running replay-parity for {base}..."):
        pr = run_parity(
            df, strat, symbol=entry.ticker, tf=entry.tf,
            starting_balance=100_000,
            lots=DEFAULT_LOTS.get(entry.ticker, 0.1),
            money_per_unit_price=resolve_money_per_unit(entry.ticker),
            commission_per_trade=3.0, slippage_per_fill_atr_frac=0.1,
            risk_cfg=cfg, symbol_info=sym_info,
        )
    elapsed = time.time() - t0
    div = pr.divergence_dollars
    cols = st.columns(4)
    cols[0].metric("BT trades", pr.bt.n_trades)
    cols[1].metric("Replay trades", pr.rp.n_trades)
    cols[2].metric("BT P&L", f"${pr.bt.sum_realized_pnl:+,.2f}")
    cols[3].metric("Divergence", f"${div:.4f}")
    if pr.passes:
        ParityGate(REPO / "data" / "v2.db").record_pass(
            base, divergence_dollars=div,
        )
        st.success(
            f"✅ Parity PASSED in {elapsed:.2f}s — divergence ${div:.6f}. "
            f"`{base}` cleared for live for the next 24h. "
            f"You can now click **🟢 Add to live** above."
        )
        st.toast(f"✅ {base} parity recorded")
    else:
        st.error(
            f"⛔ Parity FAILED — divergence ${div:.4f} > $0.01 tolerance. "
            f"BT: {pr.bt.n_trades} / ${pr.bt.sum_realized_pnl:+,.2f} vs "
            f"Replay: {pr.rp.n_trades} / ${pr.rp.sum_realized_pnl:+,.2f}. "
            f"`{base}` BLOCKED from live until engine drift is resolved."
        )


def _decode_legacy_variant_config(*, variant: str, rr_label: str) -> dict:
    """Reconstruct strategy params from a legacy markdown catalog row.

    Markdown rows (`docs/optimization_*.md` / `grid_results.md`) only
    encode the variant NAME (e.g. `ema_cross_12_26`) and the R:R LABEL
    (e.g. `1:2 wide`) — the full param dict isn't stored. To make
    deep-dive backtests reproducible without re-running the rebaseline
    script, decode both back to a config dict.

    Mirrors:
      - core.optimizer.RR_VARIANTS for stop/target atr-mults
      - scripts/optimize_portfolio._build_rr_aware for variant params

    Returns {} if the variant is unrecognised — caller falls through to
    strategy defaults (which is the pre-this-fix behaviour, and visibly
    diverges from the catalog row).
    """
    cfg: dict = {}

    # Variant name → strategy-specific params
    if variant.startswith("ema_cross_"):
        parts = variant.split("_")
        if len(parts) >= 4:
            try:
                cfg["fast_period"] = int(parts[2])
                cfg["slow_period"] = int(parts[3])
            except ValueError:
                pass
    elif variant.startswith("ema_pullback_"):
        parts = variant.split("_")
        if len(parts) >= 4:
            try:
                cfg["fast_period"] = int(parts[2])
                cfg["slow_period"] = int(parts[3])
            except ValueError:
                pass
    elif variant.startswith("donchian_"):
        try:
            cfg["period"] = int(variant.split("_")[1])
        except (ValueError, IndexError):
            pass
    elif variant.startswith("rsi_"):
        parts = variant.split("_")
        if len(parts) >= 3:
            try:
                cfg["oversold"] = int(parts[1])
                cfg["overbought"] = int(parts[2])
            except ValueError:
                pass
    elif variant.startswith("bbands_"):
        parts = variant.split("_")
        if len(parts) >= 3:
            try:
                cfg["bb_period"] = int(parts[1])
                cfg["bb_k"] = float(parts[2])
            except ValueError:
                pass

    # R:R label → stop/target atr-mults (mirrors core.optimizer.RR_VARIANTS)
    rr_table = {
        "1:1":      (1.5, 1.5),
        "1:1.5":    (1.5, 2.25),
        "1:2":      (1.5, 3.0),
        "1:3":      (1.5, 4.5),
        "1:2 wide": (2.5, 5.0),
        # 1:1.1 is donchian-specific — derived from sweep_rr_winrate
        "1:1.1":    (1.5, 1.65),
    }
    if rr_label and rr_label in rr_table:
        sm, tm = rr_table[rr_label]
        cfg["stop_atr_mult"] = sm
        cfg["target_atr_mult"] = tm

    return cfg


def _run_drilldown(entry, *, start_bal: float, train_pct: float,
                    commission: float, slippage: float = None) -> None:
    """Run the entry's backtest live and render full stats + curves.

    Pre-fix this only set `long_only` and used hard-coded
    slippage 0.10 / commission 3.0, producing metrics that diverged
    wildly from the catalog row (the catalog uses cost_defaults +
    the entry's full source_config_json with stop_atr_mult /
    target_atr_mult). E.g. ema_cross_9_20 GBPUSD D1 here showed
    "RECOVERY 1352d" while the catalog row shows recovery ≤ 90d.

    Now: pull the full config from entry.edge.source_config_json
    when present, and use cost_defaults for slippage so the inline
    deep-dive matches the catalog and the dedicated Backtest page.
    """
    import dataclasses
    import json as _json
    from core.backtest import partition_train_test, run_backtest
    from core.backtest_stats import (
        compute_full_stats, rescale_to_starting_balance,
    )
    from core.data import load_parquet
    from core import cost_defaults as _cd
    from dashboards.components.state import (
        discover_strategies, resolve_money_per_unit,
    )

    parquet = REPO / "data" / f"{entry.ticker}_{entry.tf}.parquet"
    if not parquet.exists():
        st.error(f"Parquet `{parquet.relative_to(REPO)}` missing — "
                  "use Data Manager to fetch.")
        return

    from dashboards.components.strategy_resolver import resolve_base_strategy

    strats = discover_strategies()
    base = resolve_base_strategy(entry.strategy, strats)
    if base is None:
        st.error(
            f"Strategy class for variant `{entry.strategy}` not found "
            f"in registry. Registered: {sorted(strats.keys())}"
        )
        return
    StratCls, ParamsCls = strats[base]

    # Pull stored config from the catalog row when available — this is
    # the EXACT config that produced the metrics shown in the cells
    # table, so the deep-dive will reproduce them.
    #
    # Two-tier fallback:
    #   1. v2.db rows have source_config_json populated (preferred)
    #   2. legacy markdown rows have it empty — we infer from variant
    #      name (e.g. ema_cross_12_26 → fast=12, slow=26) AND R:R label
    #      (e.g. "1:2 wide" → stop=2.5, target=5.0)
    # Without tier 2, deep-dives on legacy cells would silently use
    # strategy defaults and produce 166 trades vs catalog's 75 — exact
    # bug the user reported on ema_cross_12_26 × UK100.cash × H1.
    stored_cfg: dict = {}
    if entry.edge is not None:
        cfg_json = getattr(entry.edge, "source_config_json", "") or ""
        if cfg_json:
            try:
                stored_cfg = _json.loads(cfg_json)
            except (ValueError, TypeError):
                stored_cfg = {}
        # Tier-2 fallback: decode variant name + R:R label
        if not stored_cfg:
            stored_cfg = _decode_legacy_variant_config(
                variant=entry.strategy,
                rr_label=entry.edge.rr_label,
            )

    # Symbol_info is REQUIRED for risk%-sizing to match the catalog. The
    # rebaseline_catalog script that produced the catalog metrics uses
    # risk_pct=0.30% and symbol_info — so the deep-dive MUST also use
    # them, otherwise it falls back to fixed 0.1 lots and produces
    # ~30× smaller trade sizes (avg win $10 vs catalog's $300). That
    # turns a PF 1.54 cell into a PF 0.66 cell after fees alone.
    from core.symbol_info_loader import try_load as _try_load_si
    sym_info = _try_load_si(entry.ticker)

    with st.spinner(f"Running {entry.strategy} on {entry.ticker} {entry.tf}…"):
        df = load_parquet(parquet)
        if ParamsCls is not None:
            field_names = {f.name for f in dataclasses.fields(ParamsCls)}
            kwargs = {k: v for k, v in stored_cfg.items()
                       if k in field_names}
            # Always honour the entry's long_only flag (overrides config)
            if "long_only" in field_names:
                kwargs["long_only"] = entry.long_only
            try:
                strat = StratCls(ParamsCls(**kwargs))
            except TypeError:
                strat = StratCls()
        else:
            strat = StratCls()
        result = run_backtest(
            df, strat.signals(df),
            starting_balance=start_bal,
            lots=0.1,
            money_per_unit_price=resolve_money_per_unit(entry.ticker),
            commission_per_trade=commission,
            slippage_per_fill_atr_frac=(slippage if slippage is not None
                                          else _cd.DEFAULT_SLIPPAGE_ATR_FRAC),
            symbol=entry.ticker,
            risk_pct=(_cd.DEFAULT_RISK_PCT if sym_info is not None
                       else None),
            symbol_info=sym_info,
        )
        stats = compute_full_stats(result, starting_balance=start_bal)
    if sym_info is None:
        st.warning(
            f"⚠ symbol_info missing for `{entry.ticker}` — deep-dive "
            f"ran with fixed 0.1 lots instead of risk%-sizing. Metrics "
            f"will diverge from the catalog row. Run "
            f"`make refresh-symbol-info` to fix."
        )

    # Reconciliation banner
    div = abs(result.sum_realized_pnl - result.equity_curve_pnl)
    if result.reconciles:
        st.success(f"✅ Reconciled — divergence ${div:.4f}")
    else:
        st.error(f"⛔ Reconciliation FAILED — divergence ${div:.2f}")

    if stats.n_trades == 0:
        st.warning("Strategy generated zero trades on this parquet.")
        return

    # Headline KPI grid
    k1 = st.columns(5)
    k1[0].metric("Trades", stats.n_trades)
    k1[1].metric("Win rate", f"{stats.win_rate_pct:.1f}%",
                    delta=f"{stats.n_wins}W / {stats.n_losses}L")
    k1[2].metric("Profit factor",
                    "inf" if stats.profit_factor == float("inf")
                    else f"{stats.profit_factor:.2f}")
    k1[3].metric("Avg R", f"{stats.avg_R:+.2f}")
    k1[4].metric("Net P&L", f"${stats.sum_realized:+,.2f}")

    k2 = st.columns(5)
    k2[0].metric("Max DD", f"{stats.max_dd_pct:.1f}%",
                    delta=f"-${stats.max_dd_dollars:,.0f}",
                    delta_color="inverse")
    k2[1].metric("DD duration", f"{stats.max_dd_duration_days:.0f}d")
    k2[2].metric("Recovery",
                    "not yet" if stats.recovery_duration_days is None
                    else f"{stats.recovery_duration_days:.0f}d")
    k2[3].metric("Max consec wins", stats.max_consec_wins)
    k2[4].metric("Max consec losses", stats.max_consec_losses,
                    delta_color="inverse")

    rr = stats.risk_reward_ratio
    k3 = st.columns(5)
    k3[0].metric("Avg win", f"${stats.avg_win_dollars:+,.2f}")
    k3[1].metric("Avg loss", f"${stats.avg_loss_dollars:+,.2f}",
                    delta_color="inverse")
    k3[2].metric("R:R ratio",
                    "inf" if rr == float("inf") else f"{rr:.2f}")
    k3[3].metric("Expectancy",
                    f"${stats.expectancy_dollars:+,.2f}")
    if stats.cagr_pct is None:
        k3[4].metric("CAGR (total)",
                       f"{(stats.sum_realized / start_bal * 100):+.1f}%")
    else:
        k3[4].metric("CAGR", f"{stats.cagr_pct:+.1f}%")

    # Equity + drawdown
    eq = rescale_to_starting_balance(result, start_bal)
    if eq is not None and not eq.empty:
        eq = eq.copy()
        eq["time"] = pd.to_datetime(eq["time"], utc=True, errors="coerce")
        eq = eq.dropna(subset=["time"]).sort_values("time")
        eq["peak"] = eq["equity"].cummax()
        eq["dd_pct"] = (eq["peak"] - eq["equity"]) / eq["peak"] * 100.0
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=eq["time"], y=eq["equity"],
                                    mode="lines", name="equity",
                                    line=dict(color="#38bdf8", width=2)))
        fig.add_hline(y=start_bal,
                       line=dict(color="#6b7280", dash="dash", width=1),
                       annotation_text=f"start ${start_bal:,.0f}",
                       annotation_position="top right",
                       annotation_font=dict(color="#6b7280", size=10))
        fig.add_hline(y=start_bal * 0.95,
                       line=dict(color="#dc2626", dash="dash", width=1),
                       annotation_text="−5% FTMO daily",
                       annotation_font=dict(color="#dc2626", size=10),
                       annotation_position="bottom right")
        fig.add_hline(y=start_bal * 0.90,
                       line=dict(color="#dc2626", dash="dash", width=1),
                       annotation_text="−10% FTMO total",
                       annotation_font=dict(color="#dc2626", size=10),
                       annotation_position="bottom right")
        fig.update_layout(
            title=f"Equity from ${start_bal:,.0f}",
            height=320, margin=dict(l=10, r=10, t=40, b=10),
            plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
            font=dict(color="#cbd5e1"),
            xaxis=dict(gridcolor="#1f2937"),
            yaxis=dict(gridcolor="#1f2937"))
        st.plotly_chart(fig, width="stretch")

        # R-distribution histogram
        rs = [t.r_multiple for t in result.trades]
        fig_r = go.Figure(go.Histogram(
            x=rs, nbinsx=30,
            marker_color="#38bdf8", opacity=0.85))
        fig_r.add_vline(x=0, line=dict(color="#6b7280", dash="dash"))
        fig_r.update_layout(
            title="R-multiple distribution",
            xaxis_title="R", yaxis_title="trades",
            height=240, margin=dict(l=10, r=10, t=40, b=10),
            plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
            font=dict(color="#cbd5e1"),
            xaxis=dict(gridcolor="#1f2937"),
            yaxis=dict(gridcolor="#1f2937"))
        st.plotly_chart(fig_r, width="stretch")

    # Train/Test split
    train, test = partition_train_test(result, train_pct, n_bars=len(df))
    st.markdown(f"**Train ({train_pct*100:.0f}%) / Test "
                  f"({(1 - train_pct)*100:.0f}%) split**")
    cols_split = st.columns(2)
    for col, m in [(cols_split[0], train), (cols_split[1], test)]:
        pf_disp = "inf" if m.profit_factor == float("inf") else f"{m.profit_factor:.2f}"
        col.markdown(
            f"<div style='background:#0f1419;border:1px solid #1f2937;"
            f"border-radius:8px;padding:10px;'>"
            f"<b>{m.label.upper()}</b> · n={m.n_trades} · "
            f"PF {pf_disp} · R {m.avg_R:+.2f} · "
            f"win {m.win_rate:.1f}% · ${m.sum_pnl:+,.0f}</div>",
            unsafe_allow_html=True)

    st.caption(
        f"Largest single win: ${stats.largest_win_dollars:+,.2f}  ·  "
        f"largest single loss: ${stats.largest_loss_dollars:+,.2f}  ·  "
        f"avg trade duration: {stats.avg_trade_bars:.1f} bars  ·  "
        f"sharpe-on-R: {stats.sharpe_R:.2f}"
    )


def _summary_metrics(entries: list[strategy_library.LibraryEntry]) -> None:
    """Top-of-page KPIs: how many recommended, survivors, total."""
    n = len(entries)
    n_rec = sum(1 for e in entries if e.recommended)
    n_edge = sum(1 for e in entries if e.has_edge)
    avg_test_r = (sum(e.edge.test_r for e in entries if e.edge)
                   / max(1, sum(1 for e in entries if e.edge)))
    cols = st.columns(4)
    cols[0].metric("Total cells", n)
    cols[1].metric("Recommended ⭐", n_rec)
    cols[2].metric("Survivors (edge)", n_edge)
    cols[3].metric("Avg test_R", f"{avg_test_r:+.2f}")


def _filter_controls() -> tuple[bool, bool, str, str]:
    cols = st.columns([1, 1, 2, 2])
    only_rec = cols[0].checkbox("⭐ Recommended only", value=False,
                                  key="lib_only_rec")
    only_edge = cols[1].checkbox("✅ With edge only", value=False,
                                   key="lib_only_edge")
    ticker_filter = cols[2].text_input(
        "ticker contains…", value="",
        placeholder="e.g. USDJPY or US100",
        key="lib_ticker_filter",
    )
    tf_filter = cols[3].selectbox(
        "tf", ["all", "M15", "H1", "H4", "D1"], index=0,
        key="lib_tf_filter",
    )
    return only_rec, only_edge, ticker_filter, tf_filter


def _table(entries: list[strategy_library.LibraryEntry]) -> pd.DataFrame:
    return strategy_library.to_dataframe(entries)


def _render_distribution_chart(
        entries: list[strategy_library.LibraryEntry]) -> None:
    """Scatter plot: train_R on x, test_R on y. Each cell is a point."""
    rows = [e for e in entries if e.edge is not None]
    if not rows:
        st.caption("(no edge data yet — run `make sweep-grid`)")
        return
    fig = go.Figure()
    for is_rec in (True, False):
        bucket = [e for e in rows if e.recommended == is_rec]
        if not bucket:
            continue
        fig.add_trace(go.Scatter(
            x=[e.edge.train_r for e in bucket],
            y=[e.edge.test_r for e in bucket],
            mode="markers",
            name=("⭐ Recommended" if is_rec else "Other"),
            marker=dict(
                size=[max(8, min(30, e.edge.n_test * 0.8)) for e in bucket],
                color=("#fbbf24" if is_rec else "#38bdf8"),
                opacity=0.85, line=dict(width=1, color="#0f1419"),
            ),
            text=[f"{e.strategy} · {e.ticker} · {e.tf} · "
                  f"PF {e.edge.test_pf:.2f} · n_test {e.edge.n_test}"
                  for e in bucket],
            hovertemplate="<b>%{text}</b><br>train_R %{x:+.2f}<br>"
                          "test_R %{y:+.2f}<extra></extra>",
        ))
    # Quadrant lines + survivor box
    fig.add_hline(y=0, line=dict(color="#374151", width=1, dash="dot"))
    fig.add_vline(x=0, line=dict(color="#374151", width=1, dash="dot"))
    fig.add_shape(
        type="rect", x0=0, y0=0, x1=2, y1=2,
        fillcolor="#16a34a", opacity=0.06,
        line=dict(color="#16a34a", width=1, dash="dot"),
    )
    fig.add_annotation(
        x=1.0, y=1.9, text="survivor zone (both > 0)",
        showarrow=False, font=dict(color="#16a34a", size=10),
    )
    fig.update_layout(
        title="train_R vs test_R — bigger = more OOS trades",
        xaxis_title="train avg R-multiple",
        yaxis_title="test avg R-multiple",
        height=460, plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
        font=dict(color="#cbd5e1"),
        legend=dict(orientation="h", x=0, y=1.10),
        margin=dict(l=10, r=10, t=60, b=10),
    )
    st.plotly_chart(fig, width="stretch")


def _render_trendo_heatmap(entries) -> None:
    """Render every cell on the classic WR × R:R profitability matrix.

    Background: green zones (EV > 0) / amber (break-even) / red (negative
    EV). Each strategy cell is plotted as a marker — green dot if it
    lands in the profitable zone, red if not. User can sort their entire
    library by mathematical edge at a glance.
    """
    from core import trendo_matrix as tm

    rows = [(e.strategy, e.ticker, e.tf, e.edge.win_rate_pct,
             e.edge.rr_ratio, tm.expectancy_per_R(
                 e.edge.win_rate_pct, e.edge.rr_ratio),
             e.edge.is_trendo_profitable)
            for e in entries
            if e.edge is not None
            and e.edge.win_rate_pct > 0
            and e.edge.rr_ratio > 0]
    if not rows:
        return

    st.markdown("### 🎯  Trendo R:R × Win-Rate matrix")
    st.caption(
        "Every strategy plotted on the classic profitability grid. "
        "Green background = mathematically profitable in the long run "
        "(EV > 0). Red = negative expectancy. Markers are coloured by "
        "the cell's actual zone."
    )

    # Build the grid background
    wr_grid = [10, 20, 30, 40, 50, 60, 70, 80]
    rr_grid = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0]
    z_matrix = [[tm.expectancy_per_R(wr, rr) for wr in wr_grid]
                for rr in rr_grid]
    fig = go.Figure()
    fig.add_trace(go.Heatmap(
        x=wr_grid, y=rr_grid, z=z_matrix,
        colorscale=[[0, "#7f1d1d"], [0.5, "#7c2d12"], [0.7, "#15803d"],
                     [1, "#16a34a"]],
        zmid=0,
        showscale=True, opacity=0.45,
        colorbar=dict(title="EV per R", thickness=12),
        hovertemplate="Win %{x}%, R:R %{y}:1<br>EV = %{z:+.2f}R<extra></extra>",
    ))
    # Plot every cell as a marker
    fig.add_trace(go.Scatter(
        x=[r[3] for r in rows], y=[r[4] for r in rows],
        mode="markers",
        marker=dict(
            size=[max(8, min(22, e.edge.n_test * 0.4))
                  for e in entries
                  if e.edge is not None
                  and e.edge.win_rate_pct > 0
                  and e.edge.rr_ratio > 0],
            color=["#16a34a" if r[6] else "#dc2626" for r in rows],
            line=dict(width=1, color="#0f1419"),
            opacity=0.9,
        ),
        text=[f"{r[0]} · {r[1]} · {r[2]}<br>"
              f"WR {r[3]:.1f}%  R:R {r[4]:.2f}<br>"
              f"<b>EV {r[5]:+.2f}R</b>"
              for r in rows],
        hovertemplate="%{text}<extra></extra>",
        showlegend=False,
    ))
    # Break-even curve: WR* = 1/(1+R:R) ⟹ WR = 100/(1+R:R)
    rr_curve = [r/10 for r in range(5, 60)]
    wr_curve = [100.0 / (1.0 + r) for r in rr_curve]
    fig.add_trace(go.Scatter(
        x=wr_curve, y=rr_curve, mode="lines",
        line=dict(color="#fbbf24", width=2, dash="dash"),
        name="Break-even curve  (EV = 0)",
        hovertemplate="break-even<extra></extra>",
    ))
    fig.update_layout(
        title="Win % (x) × R:R (y) — bigger marker = more OOS trades",
        xaxis_title="Win rate %", yaxis_title="R:R ratio",
        height=480, plot_bgcolor="#0b1117", paper_bgcolor="#0b1117",
        font=dict(color="#cbd5e1"),
        xaxis=dict(gridcolor="#1f2937", range=[10, 80]),
        yaxis=dict(gridcolor="#1f2937", range=[0.5, 5.0]),
        legend=dict(orientation="h", x=0, y=1.10),
        margin=dict(l=10, r=10, t=60, b=10),
    )
    st.plotly_chart(fig, width="stretch")

    # Summary counts
    n_total = len(rows)
    n_green = sum(1 for r in rows if r[6])
    n_red = n_total - n_green
    cols = st.columns(3)
    cols[0].metric("Cells with edge (EV > 0)", n_green,
                      delta=f"{n_green/n_total*100:.0f}% of total")
    cols[1].metric("Cells losing in long run", n_red,
                      delta=f"{n_red/n_total*100:.0f}% of total",
                      delta_color="inverse")
    cols[2].metric("Mean EV per R",
                      f"{sum(r[5] for r in rows)/n_total:+.2f}R")


def main() -> None:
    st.set_page_config(page_title="Strategy Library", page_icon="🏛️",
                        layout="wide")
    theme.inject_css()
    st.title("🏛️  Strategy Library")
    st.caption(
        "Each row is a strategy × ticker × timeframe cell. Stats come from "
        "the latest `make sweep-grid` run on real broker data. The "
        "⭐ rows are the curated portfolio that pre-fills on the **Live** "
        "tab.")
    st.caption(
        f"⚖️ **Benchmark** — {cost_defaults.cost_config_badge()}. "
        f"Same cost config used by Backtest page, Composer, Compare, "
        f"sweep_grid. Run `python scripts/rebaseline_catalog.py` after "
        f"changing `core/cost_defaults.py` to refresh every cell."
    )

    cat = edge_catalog.load_catalog()
    if not cat:
        st.warning(
            "No edge data found. Run `make sweep-grid` (with the bridge "
            "running and parquets fresh) to populate "
            "`docs/grid_results.md`. Until then the Library shows the "
            "curated entries with no stats.")

    only_rec, only_edge, ticker_filter, tf_filter = _filter_controls()

    entries = strategy_library.list_library()
    if only_rec:
        entries = [e for e in entries if e.recommended]
    if only_edge:
        entries = [e for e in entries if e.has_edge]
    if ticker_filter.strip():
        ticker_filter_l = ticker_filter.strip().lower()
        entries = [e for e in entries
                    if ticker_filter_l in e.ticker.lower()]
    if tf_filter != "all":
        entries = [e for e in entries if e.tf == tf_filter]

    _summary_metrics(entries)
    st.markdown("")
    _render_distribution_chart(entries)
    st.markdown("---")
    _render_trendo_heatmap(entries)
    st.markdown("---")

    st.markdown("### Cells ranked by out-of-sample R")
    st.caption(
        "💡 Click the **📊 Backtest** link on any row to open that cell "
        "with the EXACT config that produced its metrics — fresh run "
        "reproduces these numbers. For replay-parity / deploy, scroll "
        "down to the **🔍 Deep-dive** section."
    )
    st.caption(
        "⭐ = curated **AND** passes every hard gate (PF ≥ 1.05, "
        "TEST PF ≥ 1.0, recovery ≤ 90d, n_test ≥ 20). "
        "📍 = curated but currently failing a gate (legacy entry, "
        "may need re-baseline). No icon = uncurated cell from the "
        "broader sweep."
    )
    df = _table(entries)
    if df.empty:
        st.caption("(no entries after filters)")
        return

    # Phase-32: Edge Score column from `core.edge_score`. Multi-metric
    # ranking (Kelly + expectancy + recovery×frequency + Sharpe-R +
    # deploy_safe). Strictly better than raw PF or test_R alone for
    # picking deployable cells. Default-sortable.
    from core import edge_score as _es
    edge_scores = []
    for e in entries:
        if e.edge is None:
            edge_scores.append(0.0)
            continue
        try:
            edge_scores.append(round(
                _es.compute_from_edge_stat(e.edge).total, 1
            ))
        except Exception:
            edge_scores.append(0.0)
    df["Edge Score"] = edge_scores

    # Phase-32: Edge Score explainer — same across all 4 pages
    from dashboards.components import edge_score_explainer
    edge_score_explainer.render_explainer(expanded=False)

    # Append a 📊 Backtest LinkColumn — the catalog's source_config_json
    # is embedded so a fresh run reproduces the catalog metrics. Cells
    # without an EdgeStat (legacy seed-only entries) get an empty link
    # which Streamlit renders as plain text.
    from dashboards.components.backtest_link import build_backtest_url
    df["📊 Backtest"] = [
        (build_backtest_url(e.edge) if e.edge is not None else "")
        for e in entries
    ]

    # Streamlit's LinkColumn requires a non-styled DataFrame, so we drop
    # the per-cell red/green text colour in exchange for clickable rows
    # — a UX trade the user explicitly asked for. Visual cues live in
    # the existing "Trendo EV" column (✅/🟡/🔴 emoji) and the row icons
    # ("rec" star, "edge?" ✅/—, "confidence" ✓/⚠).
    column_cfg = {
        "📊 Backtest": st.column_config.LinkColumn(
            "📊 Backtest",
            display_text="Open",
            help="Open this cell in the Backtest page with its stored "
                  "config — fresh run will reproduce these metrics.",
        ),
        "Edge Score": st.column_config.NumberColumn(
            "Edge Score",
            format="%.1f",
            help=edge_score_explainer.COLUMN_HEADER_HELP,
        ),
        "PF_test": st.column_config.NumberColumn(format="%.2f"),
        "R_test":  st.column_config.NumberColumn(format="%+.3f"),
        "win%":    st.column_config.NumberColumn(format="%.1f%%"),
        "maxDD%":  st.column_config.NumberColumn(format="%.1f%%"),
        "netPnL$": st.column_config.NumberColumn(format="$%+,.0f"),
        "avgWin$": st.column_config.NumberColumn(format="$%+,.0f"),
        "avgLoss$": st.column_config.NumberColumn(format="$%+,.0f"),
        "maxDD$":  st.column_config.NumberColumn(format="$%,.0f"),
        "rr":      st.column_config.NumberColumn(format="%.2f"),
    }
    st.dataframe(
        df, width="stretch",
        hide_index=True,
        height=min(720, 38 * (len(df) + 1)),
        column_config=column_cfg,
    )

    # ── Drill-down panel: pick a cell, run the backtest inline, show
    # full stats + equity curve + drawdown.
    st.markdown("---")
    st.markdown("### 🔍  Deep-dive into a cell")
    st.caption(
        "Pick any cell to run its backtest live and see equity curve, "
        "drawdown, R distribution, and the full stats grid.")
    if not entries:
        st.caption("(no entries to drill into)")
    else:
        # Selector icons mirror the table's `rec` column:
        #   ⭐ = curated AND deploy_safe AND n_test ≥ 20 (truly safe)
        #   📍 = curated but currently failing a hard gate
        #   (blank) = not in curated list
        def _badge(_e):
            if _e.is_starred:
                return " ⭐"
            if _e.recommended:
                return " 📍"
            return ""
        labels = {f"{e.strategy} · {e.ticker} · {e.tf}{_badge(e)}": e
                  for e in entries}
        choice = st.selectbox(
            "cell", options=list(labels.keys()),
            key="lib_drilldown_pick",
        )
        cols_in = st.columns([1, 1, 1, 1])
        start_bal = float(cols_in[0].number_input(
            "Starting balance ($)",
            value=cost_defaults.DEFAULT_STARTING_BALANCE_USD,
            step=10_000.0, min_value=1_000.0,
            key="lib_drill_start"))
        train_pct = float(cols_in[1].slider(
            "Train split %", min_value=0.5, max_value=0.9,
            value=cost_defaults.DEFAULT_TRAIN_PCT,
            step=0.05, key="lib_drill_train"))
        comm = float(cols_in[2].number_input(
            "Commission $/trade",
            value=cost_defaults.DEFAULT_COMMISSION_USD, step=0.5,
            key="lib_drill_comm"))
        slip = float(cols_in[3].number_input(
            "Slippage (× ATR)",
            value=cost_defaults.DEFAULT_SLIPPAGE_ATR_FRAC,
            step=0.05, format="%.3f", key="lib_drill_slip"))
        st.caption(
            f"⚖️ Defaults from `core.cost_defaults` — same setup the "
            f"catalog rows above were measured under, so a fresh "
            f"deep-dive run reproduces them. Override here for "
            f"what-if scenarios."
        )
        # ─── Action row 1: Inline deep-dive · Replay-parity ─────────
        # Inline backtest renders below this panel. The 📊 Open in
        # Backtest page button uses the SAME config but routes to the
        # dedicated Backtest page (URL-shareable, equity charts, etc).
        action_cols = st.columns([2, 2, 2])
        if action_cols[0].button("▶  Run deep-dive backtest",
                       type="primary",
                       width="stretch",
                       key="lib_drill_run"):
            entry = labels[choice]
            _run_drilldown(entry, start_bal=start_bal,
                            train_pct=train_pct, commission=comm,
                            slippage=slip)
        if action_cols[1].button(
            "🔬  Run replay-parity",
            width="stretch",
            key="lib_drill_parity",
            help="Verify backtest == bar-by-bar replay (must match within "
                  "$0.01) before this strategy can deploy live. PASS records "
                  "to the parity gate for 24h.",
        ):
            entry = labels[choice]
            _run_replay_parity_inline(entry)
        # 📊 Open the SAME cell in the dedicated Backtest page with the
        # full source_config_json embedded in the URL — fresh run there
        # reproduces these metrics exactly. Uses the shared helper.
        from dashboards.components.backtest_link import build_backtest_url
        _entry_for_link = labels[choice]
        if _entry_for_link.edge is not None:
            action_cols[2].link_button(
                "📊  Open in Backtest page",
                build_backtest_url(_entry_for_link.edge),
                width="stretch",
                help="Opens the dedicated Backtest page with the EXACT "
                      "config that produced this cell's catalog metrics. "
                      "Fresh run will reproduce them.",
            )
        else:
            action_cols[2].caption(
                "_(no catalog config — use inline deep-dive)_"
            )

        # ─── Action row 2: Deploy ────────────────────────────────────
        # Quality gate + parity gate status together, so the user knows
        # exactly what's blocking before they click.
        from core.deployment_quality_gate import (
            evaluate_quality as _eval_q,
            load_criteria as _load_q,
        )
        from dashboards.components.state import discover_strategies as _ds
        from dashboards.components.strategy_resolver import (
            resolve_base_strategy as _rb,
        )
        _entry_now = labels[choice]
        _gate = ParityGate(REPO / "data" / "v2.db")
        _base = _rb(_entry_now.strategy, _ds()) or _entry_now.strategy
        _parity_ok = _gate.is_recent(_base)
        _last_pass = _gate.last_pass_for(_base)

        # Quality gate verdict for the SELECTED row (with default criteria)
        if _entry_now.edge is not None:
            try:
                _q = _eval_q(_entry_now.edge, criteria=_load_q(
                    accounts := account_manager.list_accounts(),
                    accounts[0].login if accounts else 0,
                ) if False else None)
            except Exception:
                _q = _eval_q(_entry_now.edge)
        else:
            _q = None

        if _q is not None:
            if _q.is_blocked:
                with st.container(border=True):
                    st.error(
                        f"⛔ **Quality gate: BLOCK** "
                        f"({len(_q.block_reasons)} failure(s))"
                    )
                    for reason in _q.block_reasons:
                        st.markdown(f"- {reason}")
                    st.markdown(
                        "Live deploy is refused. To override (not "
                        "recommended), type `I UNDERSTAND` below "
                        "before clicking deploy. The override forces "
                        "paper mode regardless of which button you click."
                    )
            elif _q.verdict == "WARN":
                with st.container(border=True):
                    st.warning(
                        f"🟡 **Quality gate: WARN** "
                        f"({len(_q.warn_reasons)} concern(s))"
                    )
                    for reason in _q.warn_reasons:
                        st.markdown(f"- {reason}")
            else:
                st.success(
                    f"✅ Quality gate: OK "
                    f"({len(_q.pass_notes)} checks passed)"
                )

        if _parity_ok and _last_pass:
            ts = _last_pass[0].strftime("%Y-%m-%d %H:%M")
            st.success(
                f"✅ Parity OK for `{_base}` (last pass {ts} UTC, "
                f"divergence ${_last_pass[1]:.6f}). Live deploy "
                f"unlocked (subject to quality gate)."
            )
        else:
            st.warning(
                f"⚠ No recent (<24h) parity pass for `{_base}`. "
                f"Click **🔬 Run replay-parity** above to unlock live "
                f"deploy. Paper deploy works either way."
            )

        # Override-token text input — only matters when quality is BLOCK
        override_token = ""
        if _q is not None and _q.is_blocked:
            override_token = st.text_input(
                "Quality override token (type `I UNDERSTAND` to bypass)",
                value="", key="lib_quality_override",
                placeholder="leave blank to respect the BLOCK",
            )

        deploy_cols = st.columns([2, 2])
        if deploy_cols[0].button("🟡  Add to paper",
                                    width="stretch",
                                    key="lib_add_paper"):
            entry = labels[choice]
            _add_single_to_account(entry, status="paper",
                                      quality_override_token=override_token)
        # Live button disabled when EITHER gate is failing
        live_disabled = (not _parity_ok) or (_q is not None
                                                and _q.is_blocked
                                                and override_token
                                                != "I UNDERSTAND")
        if deploy_cols[1].button(
            "🟢  Add to live",
            width="stretch",
            key="lib_add_live",
            type="primary" if not live_disabled else "secondary",
            disabled=live_disabled,
            help=(None if not live_disabled
                  else "Pass replay-parity AND quality gate to unlock "
                        "(or type override token)"),
        ):
            entry = labels[choice]
            _add_single_to_account(entry, status="live",
                                      quality_override_token=override_token)

    st.markdown("---")
    st.markdown(
        "### How to use\n\n"
        "1. **Operations** (Page 0) — manage the deployments + accounts you "
        "actually run.\n"
        "2. **Strategy Library** (this page) — see the data behind every "
        "candidate, decide which to enable.\n"
        "3. **Live tab** (Page 3) — pick survivors with one click and push "
        "them into your active account's deployments.\n\n"
        "*Re-rank by running* `make sweep-grid` *after refreshing data on "
        "the Data Manager page.*"
    )


main()
