"""
edge_catalog.py — read the latest sweep_grid output so the Operations
dashboard can show each deployment's backtest edge stats inline.

Source of truth: docs/grid_results.md (regenerated by `make sweep-grid`).
This is intentionally read-only and tolerant — if the file is absent or
malformed we degrade to "no stats", we never raise.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GRID_PATH = REPO_ROOT / "docs" / "grid_results.md"


def _latest_optimization_path() -> Path | None:
    """Return the most recent docs/optimization_*.md, or None if absent."""
    docs = REPO_ROOT / "docs"
    if not docs.exists():
        return None
    candidates = sorted(docs.glob("optimization_*.md"))
    return candidates[-1] if candidates else None


@dataclass(frozen=True)
class EdgeStat:
    ticker: str
    tf: str
    strategy: str          # short label e.g. 'ema_cross_9_20'
    n_train: int
    train_pf: float
    train_r: float
    n_test: int
    test_pf: float
    test_r: float

    @property
    def total_trades(self) -> int:
        return int(self.n_train + self.n_test)

    @property
    def is_survivor(self) -> bool:
        return (self.train_pf >= 1.0 and self.test_pf >= 1.0
                and self.train_r > 0 and self.test_r > 0
                and self.n_test >= 5)


_NUM_RE = re.compile(r"[+-]?\d+(?:\.\d+)?")


def _parse_md_table(md_text: str) -> list[EdgeStat]:
    """Parse any | ticker | tf | strategy | … | tables in the markdown.

    Supports two layouts:
      • grid_results.md      9-col   ticker, tf, strategy, n_train,
                                       train_PF, train_R, n_test,
                                       test_PF, test_R
      • optimization_*.md   17-col   rank, strategy, ticker, tf, R:R, n,
                                       PF, R, win%, maxDD%, recov_d,
                                       streak, rr, CAGR, P(pass), sus, score
                              — only test_pf, test_r, n filled; train_*
                              defaulted to OOS values so survivor logic
                              still works.
    """
    out: list[EdgeStat] = []
    in_table = False
    layout: str | None = None    # 'grid' | 'opt'
    header_cells: list[str] = []
    for line in md_text.splitlines():
        if line.startswith("|") and "ticker" in line and "tf" in line:
            header_cells = [c.strip().lower()
                             for c in line.strip("|").split("|")]
            # Optimization layout starts with 'rank' before strategy
            layout = "opt" if header_cells[0] == "rank" else "grid"
            in_table = True
            continue
        if in_table and line.startswith("|---"):
            continue
        if in_table:
            if not line.startswith("|"):
                in_table = False
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            try:
                if layout == "grid" and len(cells) >= 9:
                    tic, tf, strat, n_tr, tr_pf, tr_r, n_te, te_pf, te_r = cells[:9]
                    out.append(EdgeStat(
                        ticker=tic, tf=tf, strategy=strat,
                        n_train=int(_NUM_RE.search(n_tr).group()),
                        train_pf=float(_NUM_RE.search(tr_pf).group()),
                        train_r=float(_NUM_RE.search(tr_r).group()),
                        n_test=int(_NUM_RE.search(n_te).group()),
                        test_pf=float(_NUM_RE.search(te_pf).group()),
                        test_r=float(_NUM_RE.search(te_r).group()),
                    ))
                elif layout == "opt" and len(cells) >= 8:
                    # rank | strategy | ticker | tf | R:R | n | PF | R | …
                    _, strat, tic, tf, _rr, n, pf, r = cells[:8]
                    # Cells are wrapped in backticks in the markdown
                    strat = strat.strip("` ")
                    tic = tic.strip("` ")
                    tf = tf.strip("` ")
                    n_test = int(_NUM_RE.search(n).group())
                    test_pf = (5.0 if "inf" in pf
                                else float(_NUM_RE.search(pf).group()))
                    test_r = float(_NUM_RE.search(r).group())
                    out.append(EdgeStat(
                        ticker=tic, tf=tf,
                        strategy=strat,
                        n_train=n_test,        # optimizer reports OOS only
                        train_pf=test_pf,
                        train_r=test_r,
                        n_test=n_test,
                        test_pf=test_pf,
                        test_r=test_r,
                    ))
            except (AttributeError, ValueError):
                continue
    return out


def load_catalog(path: Path | None = None) -> dict[tuple[str, str], list[EdgeStat]]:
    """Return {(ticker, tf): [EdgeStat, ...]}. Empty dict if no data.

    When `path` is None, loads BOTH the default grid_results.md AND
    every `docs/optimization_*.md`. Optimizer entries take precedence
    (de-duped by (ticker, tf, strategy) — first seen wins, with
    optimizer files iterated newest-first).
    """
    if path is not None:
        sources = [path]
    else:
        # Scan the same dir as DEFAULT_GRID_PATH so test monkeypatching
        # of that constant also redirects the optimization-file scan.
        docs = DEFAULT_GRID_PATH.parent
        sources = []
        if docs.exists():
            # Newest optimization files first → they win the de-dupe
            sources.extend(sorted(docs.glob("optimization_*.md"),
                                    reverse=True))
        sources.append(DEFAULT_GRID_PATH)

    out: dict[tuple[str, str], list[EdgeStat]] = {}
    seen: set[tuple[str, str, str]] = set()

    for p in sources:
        if not p.exists():
            continue
        try:
            text = p.read_text()
        except OSError:
            continue
        for r in _parse_md_table(text):
            key = (r.ticker, r.tf, r.strategy)
            if key in seen:
                continue
            seen.add(key)
            out.setdefault((r.ticker, r.tf), []).append(r)
    return out


def best_for(ticker: str, tf: str, strategy_prefix: str | None = None,
             *, path: Path | None = None) -> EdgeStat | None:
    """Return the best EdgeStat for (ticker, tf) optionally filtered by a
    strategy name prefix (e.g. 'ema_cross' matches 'ema_cross_9_20' and
    'ema_cross_12_26'). 'Best' = highest test_r."""
    cat = load_catalog(path)
    rows = cat.get((ticker, tf), [])
    if strategy_prefix:
        rows = [r for r in rows if r.strategy.startswith(strategy_prefix)]
    if not rows:
        return None
    return max(rows, key=lambda r: r.test_r)
