"""
strategy_library.py — what the dashboard considers a "deployable" strategy.

A `LibraryEntry` is a (strategy × ticker × tf × long_only) tuple plus the
backtest stats needed to make a deployment decision: profit factor,
average R, win rate, max drawdown in R, n_test, recommendation level.

Source of truth for stats: docs/grid_results.md (regenerated by
`make sweep-grid`). Without that file, we still expose the strategy list
but with empty stats.

The LIBRARY is not just "every strategy" — it's the OPINIONATED list a
new operator should consider. Each entry has a `recommended` flag that
the dashboard uses to pre-check the deployment selector.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from core import edge_catalog


# ---------------------------------------------------------------------------
# Static recommendation list — the survivors from the latest grid sweep.
# Each row: (strategy_prefix, ticker, tf, long_only, why)
#
# `strategy_prefix` matches edge_catalog rows (e.g. 'ema_cross' picks the
# best of ema_cross_9_20 / ema_cross_12_26).  We let the catalog choose
# the parameter variant.
# ---------------------------------------------------------------------------
RECOMMENDED_PORTFOLIO: list[tuple[str, str, str, bool, str]] = [
    ("ema_cross",     "USDJPY",     "D1", True,
     "Strongest test_R in the grid (+0.95)."),
    ("ema_cross",     "GBPJPY",     "D1", True,
     "Second-strongest cross-pair (+0.94 test_R)."),
    ("ema_cross",     "GBPUSD",     "D1", True,
     "Cleanest D1 cross (test_PF 2.18, 13 OOS)."),
    ("donchian",      "US100.cash", "D1", True,
     "Index breakout — long history, 19 OOS trades."),
    ("ema_cross",     "US100.cash", "D1", True,
     "Index trend follower (test_PF 2.39)."),
    ("rsi_meanrev",   "GBPUSD",     "D1", True,
     "Mean-revert outlier (test_PF 4.95)."),
    ("ema_pullback",  "GBPJPY",     "D1", True,
     "Pullback continuation on JPY pair."),
    ("rsi_meanrev",   "EURUSD",    "M15", True,
     "Highest-frequency survivor (41 OOS trades)."),
    ("ema_cross",     "USDJPY",    "M15", True,
     "M15 trend follower with high sample count."),
]


@dataclass(frozen=True)
class LibraryEntry:
    strategy: str
    ticker: str
    tf: str
    long_only: bool
    recommended: bool
    why: str = ""
    edge: Optional[edge_catalog.EdgeStat] = None

    @property
    def slug(self) -> str:
        side = "long" if self.long_only else "bidir"
        return f"{self.strategy}__{self.ticker}__{self.tf}__{side}"

    @property
    def has_edge(self) -> bool:
        return self.edge is not None and self.edge.is_survivor

    @property
    def is_starred(self) -> bool:
        """Show ⭐ in UIs only if the cell is in the curated list AND
        passes every hard gate AND has enough OOS sample to be robust
        across small split-method drift (n_test ≥ 20, not just ≥ 15).

        Pre-fix the Library showed ⭐ on cells where the catalog's
        n_test=16 passes the n_test ≥ 15 gate but the fresh Backtest's
        OOS partition has 13 trades and fails. The user saw ⭐ AND
        "FAILS gates" simultaneously. Tightening the threshold to 20
        gives a buffer for split-method differences (catalog splits
        by trade count, Backtest by bar index).
        """
        if not self.recommended:
            return False
        if self.edge is None:
            return False
        if not getattr(self.edge, "deploy_safe", True):
            return False
        if self.edge.n_test < 20:
            return False
        return True


def list_library(*, only_with_edge: bool = False) -> list[LibraryEntry]:
    """Return the curated library, sorted recommended-first then by test_R desc."""
    cat = edge_catalog.load_catalog()
    out: list[LibraryEntry] = []
    seen: set[tuple[str, str, str, bool]] = set()

    # 1. Recommended portfolio entries first (in declared order)
    for strat_prefix, ticker, tf, long_only, why in RECOMMENDED_PORTFOLIO:
        es = edge_catalog.best_for(ticker, tf, strat_prefix)
        if es is None:
            continue   # silently drop entries the catalog can't back
        key = (es.strategy, ticker, tf, long_only)
        if key in seen:
            continue
        seen.add(key)
        out.append(LibraryEntry(
            strategy=es.strategy, ticker=ticker, tf=tf, long_only=long_only,
            recommended=True, why=why, edge=es,
        ))

    # 2. Every other surviving cell from the grid
    for (ticker, tf), rows in cat.items():
        for es in rows:
            key = (es.strategy, ticker, tf, True)   # default long-only
            if key in seen:
                continue
            seen.add(key)
            if only_with_edge and not es.is_survivor:
                continue
            out.append(LibraryEntry(
                strategy=es.strategy, ticker=ticker, tf=tf, long_only=True,
                recommended=False, why="", edge=es,
            ))

    # Sort: recommended first; within each group by test_R desc
    def _sort_key(e: LibraryEntry) -> tuple[int, float]:
        return (0 if e.recommended else 1,
                -(e.edge.test_r if e.edge else -999.0))
    out.sort(key=_sort_key)
    return out


def to_dataframe(entries: list[LibraryEntry]):
    """Pandas DataFrame for the Strategy Library table view.

    AlgoTest-style columns: every survivor surfaces R:R variant, max DD$,
    DD-period in days, recovery time, avg win$, avg loss$, net P&L$ on
    a $100k baseline.

    A `confidence` column flags small-sample cells: ⚠ if n_test < 10
    (statistically unreliable), ✓ if n_test ≥ 10. The threshold is the
    same the optimizer uses to keep cells (--min-oos-trades).
    """
    import pandas as pd
    rows = []
    for e in entries:
        es = e.edge
        n = es.n_test if es else 0
        # Confidence band: < 10 trades is too few to trust the statistic.
        # 10–29 is moderate, 30+ is good.
        if not es or n < 10:
            confidence = "⚠ low"
        elif n < 30:
            confidence = "~ medium"
        else:
            confidence = "✓ high"
        # Trendo zone — ✅/🟡/🔴 based on the WR × R:R profitability matrix
        if es and es.win_rate_pct > 0 and es.rr_ratio > 0:
            from core import trendo_matrix
            ev = trendo_matrix.expectancy_per_R(es.win_rate_pct,
                                                   es.rr_ratio)
            zone_icon = {
                "green": "✅", "amber": "🟡", "red": "🔴"
            }[trendo_matrix.trendo_zone(es.win_rate_pct, es.rr_ratio)]
            trendo_label = f"{zone_icon} {ev:+.2f}R"
        else:
            trendo_label = "—"
        # ⭐ ONLY when the cell is curated-recommended AND deploy-safe
        # AND has enough OOS sample. Without all three, the ⭐ misleads
        # the user into clicking Backtest and seeing the cell get
        # rejected by the hard gates — see is_starred docstring.
        rows.append({
            "rec": "⭐" if e.is_starred else
                    ("📍" if e.recommended else ""),
            "confidence": confidence,
            "Trendo EV": trendo_label,
            "strategy": e.strategy,
            "ticker": e.ticker,
            "tf": e.tf,
            "side": (es.side if es and es.side else
                     ("long" if e.long_only else "bidir")),
            "R:R": (es.rr_label if es else "") or "—",
            "n_test": n if es else None,
            "PF_test": round(es.test_pf, 2) if es else None,
            "R_test": round(es.test_r, 3) if es else None,
            "win%": round(es.win_rate_pct, 1) if es else None,
            "netPnL$": round(es.net_pnl_dollars) if es else None,
            "maxDD%": round(es.max_dd_pct, 1) if es else None,
            "maxDD$": round(es.max_dd_dollars) if es else None,
            "DDdays": round(es.max_dd_days) if es else None,
            "recovD": (None if not es else
                       (None if es.recovery_days is None
                        else round(es.recovery_days))),
            "rr": round(es.rr_ratio, 2) if es and es.rr_ratio else None,
            "avgWin$": round(es.avg_win_dollars) if es else None,
            "avgLoss$": round(es.avg_loss_dollars) if es else None,
            "P(pass)": (None if not es or es.p_pass_30d is None
                        else f"{es.p_pass_30d*100:.0f}%"),
            "edge?": "✅" if (es and es.is_survivor) else "—",
            "why": e.why or "",
            "slug": e.slug,
        })
    return pd.DataFrame(rows)
