#!/usr/bin/env bash
# install_runner_launchagent.sh — make the deployment runner survive
# reboots, sleep/wake, and unattended operation for weeks at a time.
#
# What it does:
#   • Creates ~/Library/LaunchAgents/com.user.mt5_runner.plist
#   • macOS launchd will:
#       - start the runner at every login
#       - restart it within 10s if it crashes
#       - keep it running through laptop sleep/wake (waking the
#         daemon when the machine resumes)
#   • Logs go to /tmp/mt5_runner.log (stdout) + /tmp/mt5_runner.err
#
# Combined with `make keep-mt5-alive-launchagent`, this is the
# vacation-grade setup: leave the laptop running, both LaunchAgents
# auto-start at every login, and the system trades 24/5 unattended.
#
# Uninstall:
#   launchctl unload ~/Library/LaunchAgents/com.user.mt5_runner.plist
#   rm ~/Library/LaunchAgents/com.user.mt5_runner.plist

set -e
trap 'echo "Aborted."; exit 0' INT TERM

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PYBIN="${REPO_DIR}/.venv/bin/python"
RUNNER="${REPO_DIR}/scripts/run_deployments.py"
PLIST="${HOME}/Library/LaunchAgents/com.user.mt5_runner.plist"

if [[ ! -x "$PYBIN" ]]; then
  echo "⛔ venv not found at $PYBIN — run 'make setup' first."
  exit 1
fi
if [[ ! -f "$RUNNER" ]]; then
  echo "⛔ runner script not found at $RUNNER"
  exit 1
fi

# macOS Privacy controls block LaunchAgents from executing files in
# ~/Documents, ~/Desktop, ~/Downloads (TCC: "Operation not permitted").
# Wrap the launch in a small shim that lives outside Documents, so the
# LaunchAgent always has permission to run its entrypoint regardless of
# Full Disk Access settings.
INSTALL_DIR="${HOME}/Library/Application Support/mt5_quant_trader"
mkdir -p "$INSTALL_DIR"
SHIM="${INSTALL_DIR}/run_deployments_launcher.sh"
cat > "$SHIM" <<SHIMEOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_runner_launchagent.sh — do not hand-edit.
# Lives outside ~/Documents so macOS TCC permits the LaunchAgent to exec it.
cd "${REPO_DIR}"
export PYTHONPATH="${REPO_DIR}"
exec "${PYBIN}" "${RUNNER}" "\$@"
SHIMEOF
chmod +x "$SHIM"

echo "📍 Repo:    $REPO_DIR"
echo "📍 Python:  $PYBIN"
echo "📍 Runner:  $RUNNER"
echo "📍 Shim:    $SHIM   ← lives outside Documents, TCC-safe"
echo "📍 Plist:   $PLIST"
echo

mkdir -p "${HOME}/Library/LaunchAgents"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.mt5_runner</string>
    <key>ProgramArguments</key>
    <array>
        <string>${SHIM}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${REPO_DIR}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PYTHONPATH</key>
        <string>${REPO_DIR}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>/tmp/mt5_runner.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/mt5_runner.err</string>
</dict>
</plist>
EOF

# Reload (if previously installed)
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo "✅ LaunchAgent installed and started."
echo
echo "  Status:        launchctl list | grep mt5_runner"
echo "  Live log:      tail -f /tmp/mt5_runner.log"
echo "  Errors:        tail -f /tmp/mt5_runner.err"
echo "  Stop:          launchctl unload $PLIST"
echo "  Reload:        launchctl unload $PLIST && launchctl load $PLIST"
echo
echo "📌 Combined with 'make keep-mt5-alive-launchagent', the system"
echo "    will trade unattended through reboots, sleep/wake, and crashes."
