#!/usr/bin/env bash
# install_rebaseline_launchagent.sh — schedule weekly catalog
# rebaseline so the Edge Score never drifts more than 7 days behind
# the cost model.
#
# What it does:
#   • Creates ~/Library/LaunchAgents/com.user.mt5_rebaseline.plist
#   • Runs scripts/rebaseline_catalog.py every Sunday at 22:00 UTC
#     (a quiet time outside FTMO trading hours, so the runner is
#     never competing with rebaseline for compute)
#   • Logs to /tmp/mt5_rebaseline.log + /tmp/mt5_rebaseline.err
#
# Why weekly:
#   • Catalog cells are cost-priced from historical data; new bars
#     accumulate daily but the catalog's PF / R / DD numbers are
#     static between rebaselines
#   • A 7-day re-eval keeps drift < 1 trading week — comparable to
#     the autolearner's rolling-30-trade window cadence
#   • More frequent (e.g. nightly) wastes compute; less frequent
#     means the autolearner's catalog_R reference goes stale
#
# Uninstall:
#   launchctl unload ~/Library/LaunchAgents/com.user.mt5_rebaseline.plist
#   rm ~/Library/LaunchAgents/com.user.mt5_rebaseline.plist

set -e
trap 'echo "Aborted."; exit 0' INT TERM

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PYBIN="${REPO_DIR}/.venv/bin/python"
SCRIPT="${REPO_DIR}/scripts/rebaseline_catalog.py"
PLIST="${HOME}/Library/LaunchAgents/com.user.mt5_rebaseline.plist"

if [[ ! -x "$PYBIN" ]]; then
  echo "⛔ venv not found at $PYBIN — run 'make setup' first."
  exit 1
fi
if [[ ! -f "$SCRIPT" ]]; then
  echo "⛔ rebaseline script not found at $SCRIPT"
  exit 1
fi

# Same TCC-aware shim pattern as the runner LaunchAgent — install
# the launcher outside ~/Documents so macOS Privacy controls don't
# block exec.
INSTALL_DIR="${HOME}/Library/Application Support/mt5_quant_trader"
mkdir -p "$INSTALL_DIR"
SHIM="${INSTALL_DIR}/rebaseline_launcher.sh"
cat > "$SHIM" <<SHIMEOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_rebaseline_launchagent.sh —
# do not hand-edit. Lives outside ~/Documents so macOS TCC permits
# the LaunchAgent to exec it.
cd "${REPO_DIR}"
exec "${PYBIN}" "${SCRIPT}" >> /tmp/mt5_rebaseline.log 2>> /tmp/mt5_rebaseline.err
SHIMEOF
chmod +x "$SHIM"

# Schedule: every Sunday at 22:00 UTC (= 23:00 BST / 18:00 EST winter,
# 17:00 EDT summer — outside FTMO weekend rollover at 22:00 UTC Sunday).
# StartCalendarInterval interprets times in LOCAL time on macOS, so we
# can't easily set "22:00 UTC" — set 22:00 local which is close enough
# for a weekly cadence (drift of ±5h doesn't matter for a 7-day window).
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.user.mt5_rebaseline</string>
  <key>ProgramArguments</key>
  <array>
    <string>${SHIM}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Weekday</key>
    <integer>0</integer>
    <key>Hour</key>
    <integer>22</integer>
    <key>Minute</key>
    <integer>0</integer>
  </dict>
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>/tmp/mt5_rebaseline.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/mt5_rebaseline.err</string>
  <key>WorkingDirectory</key>
  <string>${REPO_DIR}</string>
</dict>
</plist>
PLISTEOF

# Reload — bootstrap+kickstart the modern way; fall back to load if
# bootstrap fails (already loaded etc.)
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo "✅ Rebaseline LaunchAgent installed:"
echo "   plist:    $PLIST"
echo "   shim:     $SHIM"
echo "   schedule: every Sunday at 22:00 local time"
echo "   logs:     /tmp/mt5_rebaseline.log, /tmp/mt5_rebaseline.err"
echo ""
echo "Next run: $(launchctl list | grep mt5_rebaseline || echo '(not yet listed by launchctl)')"
echo ""
echo "To trigger a manual rebaseline right now (test the wiring):"
echo "  bash $SHIM"
echo ""
echo "Uninstall:"
echo "  launchctl unload \"$PLIST\" && rm \"$PLIST\""
