#!/usr/bin/env python3
"""
strategy_to_mql5.py — generate an MQL5 EA scaffold from a Python strategy.

This is INTENTIONALLY a partial translator: many pandas/numpy operations
have no clean MQL5 equivalent. The script reads the Python strategy class,
extracts its Params dataclass + the signals() docstring, and emits an MQL5
.mq5 file with the same param shape and a TODO-driven OnTick() body. The
user finishes the translation by hand, then compiles in MetaEditor.

Output goes to mql5/<StrategyName>.mq5.

Usage:
    python scripts/strategy_to_mql5.py --strategy vol_breakout
"""
from __future__ import annotations

import argparse
import dataclasses
import importlib
import inspect
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _params_inputs_block(params_cls) -> str:
    """Render a Params dataclass as MQL5 'input' declarations."""
    lines = []
    for f in dataclasses.fields(params_cls):
        default = f.default
        if isinstance(default, bool):
            mql_t = "bool"
            mql_v = "true" if default else "false"
        elif isinstance(default, int):
            mql_t = "int"
            mql_v = str(default)
        elif isinstance(default, float):
            mql_t = "double"
            mql_v = f"{default:.4f}"
        else:
            mql_t = "string"
            mql_v = f'"{default}"'
        lines.append(f"input {mql_t} Inp_{f.name} = {mql_v};")
    return "\n".join(lines)


def _import(name: str):
    mod = importlib.import_module(f"strategies.{name}")
    strat_cls = None
    params_cls = None
    for clsname, cls in inspect.getmembers(mod, inspect.isclass):
        if cls.__module__ != mod.__name__:
            continue
        if dataclasses.is_dataclass(cls) and clsname.endswith("Params"):
            params_cls = cls
        elif (hasattr(cls, "name") and isinstance(cls.name, str)
              and hasattr(cls, "signals")
              and not dataclasses.is_dataclass(cls)):
            strat_cls = cls
    if strat_cls is None:
        raise SystemExit(f"no strategy class found in strategies/{name}.py")
    return strat_cls, params_cls


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strategy", required=True)
    ap.add_argument("--output", default=None,
                     help="output path (default mql5/<StrategyName>.mq5)")
    ap.add_argument("--magic", type=int, default=770_070)
    args = ap.parse_args()

    StratCls, ParamsCls = _import(args.strategy)
    cls_name = StratCls.__name__
    py_source = inspect.getsource(StratCls).rstrip()

    out_path = Path(args.output) if args.output else (
        REPO / "mql5" / f"{cls_name}.mq5"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)

    inputs = _params_inputs_block(ParamsCls) if ParamsCls else "// no Params"
    py_source_block = "\n".join(f"//  {ln}" for ln in py_source.splitlines())

    body = f'''//+------------------------------------------------------------------+
//|  {cls_name}.mq5 — generated by scripts/strategy_to_mql5.py
//|  Source: strategies/{args.strategy}.py
//|
//|  This is a SCAFFOLD. The Python signals() logic is shown below as a
//|  comment block — translate it into the OnTick handler manually, then
//|  compile (F7) and drop on a chart matching the Python backtest's
//|  ticker / TF / date range.
//+------------------------------------------------------------------+
#property copyright "v2_quant_trader auto-generated"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

CTrade trade;

input int Inp_MagicNumber = {args.magic};

// ----- Strategy params (mirrors the Python Params dataclass) -----
{inputs}

//+------------------------------------------------------------------+
int OnInit()
{{
    trade.SetExpertMagicNumber(Inp_MagicNumber);
    Print("EA {cls_name}: init ok, magic=", Inp_MagicNumber);
    return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
    // TODO: translate the Python signals() body below into MQL5.
    // The Python is comment-only here for reference — you can keep it
    // alongside the translated MQL5 to cross-check.
    //
    // Use iClose/iHigh/iLow/iOpen for OHLC.
    // Indicators: iATR, iRSI, iMA, etc. Cache handle in OnInit if needed.
    // Place order: trade.Buy(lots, NULL, sl, tp); / trade.Sell(...).
    //
    // Magic number {args.magic} is set in OnInit so this EA's trades are
    // identifiable in the Strategy Tester report (export to CSV → run
    // scripts/mt5_parity_check.py to compare with Python backtest).
}}

//+------------------------------------------------------------------+
//|  Original Python source (reference; do NOT compile)
//+------------------------------------------------------------------+
{py_source_block}
'''
    out_path.write_text(body)
    print(f"[strategy_to_mql5] wrote {out_path.relative_to(REPO)}")
    print(f"  next: open in MetaEditor (F7), translate the OnTick body, compile.")


if __name__ == "__main__":
    main()
