//+------------------------------------------------------------------+
//|  VolBreakout.mq5 — generated by scripts/strategy_to_mql5.py
//|  Source: strategies/vol_breakout.py
//|
//|  This is a SCAFFOLD. The Python signals() logic is shown below as a
//|  comment block — translate it into the OnTick handler manually, then
//|  compile (F7) and drop on a chart matching the Python backtest's
//|  ticker / TF / date range.
//+------------------------------------------------------------------+
#property copyright "v2_quant_trader auto-generated"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

CTrade trade;

input int Inp_MagicNumber = 770070;

// ----- Strategy params (mirrors the Python Params dataclass) -----
input double Inp_k = 0.5000;
input double Inp_target_R_mult = 2.0000;
input bool Inp_long_only = false;

//+------------------------------------------------------------------+
int OnInit()
{
    trade.SetExpertMagicNumber(Inp_MagicNumber);
    Print("EA VolBreakout: init ok, magic=", Inp_MagicNumber);
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnTick()
{
    // TODO: translate the Python signals() body below into MQL5.
    // The Python is comment-only here for reference — you can keep it
    // alongside the translated MQL5 to cross-check.
    //
    // Use iClose/iHigh/iLow/iOpen for OHLC.
    // Indicators: iATR, iRSI, iMA, etc. Cache handle in OnInit if needed.
    // Place order: trade.Buy(lots, NULL, sl, tp); / trade.Sell(...).
    //
    // Magic number 770070 is set in OnInit so this EA's trades are
    // identifiable in the Strategy Tester report (export to CSV → run
    // scripts/mt5_parity_check.py to compare with Python backtest).
}

//+------------------------------------------------------------------+
//|  Original Python source (reference; do NOT compile)
//+------------------------------------------------------------------+
//  class VolBreakout:
//      name = "vol_breakout"
//  
//      def __init__(self, params: VolBreakoutParams = VolBreakoutParams()):
//          self.params = params
//  
//      def signals(self, candles: pd.DataFrame) -> list[Signal]:
//          p = self.params
//          n = len(candles)
//          if n < 3:
//              return []
//  
//          o = candles["open"].to_numpy()
//          h = candles["high"].to_numpy()
//          l = candles["low"].to_numpy()
//  
//          out: list[Signal] = []
//          for i in range(1, n):
//              rng_prev = h[i - 1] - l[i - 1]
//              if rng_prev <= 0:
//                  continue
//              buy_trig = float(o[i] + p.k * rng_prev)
//              sell_trig = float(o[i] - p.k * rng_prev)
//              hit_buy = h[i] >= buy_trig
//              hit_sell = l[i] <= sell_trig
//              if hit_buy and hit_sell:
//                  # Ambiguous order; skip (conservative).
//                  continue
//              if hit_buy:
//                  entry = buy_trig
//                  stop = sell_trig   # opposite trigger
//                  risk = entry - stop
//                  if risk <= 0:
//                      continue
//                  target = entry + p.target_R_mult * risk
//                  out.append(Signal(
//                      bar_idx=i, direction="LONG",
//                      entry_price=entry, stop_price=stop,
//                      target_price=target,
//                      reason="vol_breakout_long_trigger_hit",
//                  ))
//                  continue
//              if hit_sell and not p.long_only:
//                  entry = sell_trig
//                  stop = buy_trig
//                  risk = stop - entry
//                  if risk <= 0:
//                      continue
//                  target = entry - p.target_R_mult * risk
//                  if target <= 0:
//                      continue
//                  out.append(Signal(
//                      bar_idx=i, direction="SHORT",
//                      entry_price=entry, stop_price=stop,
//                      target_price=target,
//                      reason="vol_breakout_short_trigger_hit",
//                  ))
//          return out
